name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm i
      - run: pnpm codecheck
