name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - run: bun install --frozen-lockfile

      - run: bun run lint

      - run: bun run build

      - name: setup github pages
        uses: actions/configure-pages@v4

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
